version: "3.8"
services:
  client:
    build: ./client
    environment:
      - TARGET_URL=https://envoy:8443
    depends_on:
      - envoy
    networks:
      - app_network

  server:
    build: ./server
    expose:
      - "5000"
    networks:
      - app_network

  envoy:
    image: envoyproxy/envoy:v1.25-latest
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./envoy/certs:/etc/envoy/certs
      - ./envoy/ratelimit:/etc/envoy/ratelimit
    ports:
      - "8443:8443"  # HTTPS
      - "8001:8001"  # Admin
    command: ["-c", "/etc/envoy/envoy.yaml", "--service-cluster", "proxy-cluster"]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge