version: "3.9"

services:
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    container_name: envoy
    ports:
      - "8080:8080"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    environment:
      - ENVOY_LOG_LEVEL=debug
    depends_on:
      - backend
      - ratelimit

  backend:
    build: ./app
    container_name: backend
    expose:
      - "8000"

  # REMOVIDO o serviço OPA
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

  ratelimit:
    image: envoyproxy/ratelimit:master
    container_name: ratelimit
    ports:
      - "8081:8081"
    volumes:
      - ./ratelimit/config:/data/ratelimit/config:ro
      - ./ratelimit/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    depends_on:
      - redis
    environment:
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - LOG_LEVEL=debug

  opa:
    build: ./opa
    ports:
      - "8181:8181"
    volumes:
      - ./opa/policies:/policies